localsearch: localsearch.cpp rand.cpp bithelpers.cpp 
	g++ -o localsearch localsearch.cpp rand.cpp bithelpers.cpp

run: localsearch
	./localsearch 1 0

tar:
	tar -cvf pas1.tar localsearch.cpp rand.cpp bithelpers.cpp rand.h bitHelpers.h makefile wang.pdf